# Generated by Django 2.1.2 on 2019-12-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_stage', models.IntegerField(blank=True, choices=[(1, 'Lead Received'), (2, 'Preparation for Initial Meeting'), (3, 'Qualification/Needs Analysis'), (4, 'Proposal/\u200bPrice Quote'), (5, 'Implementation\u200b  (Closed Won)\u200b'), (6, 'Closed Lost')], null=True, verbose_name='Sales Stage')),
                ('contact_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Name')),
                ('email', models.CharField(blank=True, max_length=20, null=True, verbose_name='E-mail')),
                ('company_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Company Name')),
                ('lead_from', models.IntegerField(blank=True, choices=[(1, 'Cold call/e-mail'), (2, 'Web to lead'), (3, 'Referral')], null=True, verbose_name='Lead From')),
                ('lead_received_date', models.DateField(blank=True, null=True, verbose_name='Lead Received Date')),
                ('initial_meeting_date', models.DateField(blank=True, null=True, verbose_name='Initial Meeting Date')),
                ('estimated_closed_date', models.DateField(blank=True, null=True, verbose_name='Estimated Closed Date')),
                ('deal_size', models.FloatField(blank=True, null=True, verbose_name='Deal Size [USD]')),
                ('probability_of_deal', models.IntegerField(blank=True, null=True, verbose_name='Probability of Deal [%]')),
                ('forecast', models.FloatField(blank=True, null=True, verbose_name='Forecast [USD]')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Created datetime')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Updated datetime')),
            ],
            options={
                'verbose_name': 'Sales Pipeline',
                'verbose_name_plural': 'Sales Pipeline',
            },
        ),
    ]
